name: Keep Streamlit App Alive

on:
  schedule:
    # every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:   # allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: |
          curl -fsS https://vadataapp-ngmwjwtn8mhuanv7x7q2yd.streamlit.app/ || true
